// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: publiccontent.proto

package publiccontentservice

import (
	"context"

	"GoFlix/services/content/public/publicContentRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserContentListReq  = publicContentRpc.GetUserContentListReq
	GetUserContentListResp = publicContentRpc.GetUserContentListResp

	PublicContentService interface {
		GetUserContentList(ctx context.Context, in *GetUserContentListReq, opts ...grpc.CallOption) (*GetUserContentListResp, error)
	}

	defaultPublicContentService struct {
		cli zrpc.Client
	}
)

func NewPublicContentService(cli zrpc.Client) PublicContentService {
	return &defaultPublicContentService{
		cli: cli,
	}
}

func (m *defaultPublicContentService) GetUserContentList(ctx context.Context, in *GetUserContentListReq, opts ...grpc.CallOption) (*GetUserContentListResp, error) {
	client := publicContentRpc.NewPublicContentServiceClient(m.cli.Conn())
	return client.GetUserContentList(ctx, in, opts...)
}
