// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/like.proto

package likeRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    int32                  `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	LikeId        int64                  `protobuf:"varint,3,opt,name=likeId,proto3" json:"likeId,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeReq) Reset() {
	*x = LikeReq{}
	mi := &file_proto_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeReq) ProtoMessage() {}

func (x *LikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeReq.ProtoReflect.Descriptor instead.
func (*LikeReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{0}
}

func (x *LikeReq) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *LikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeReq) GetLikeId() int64 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

func (x *LikeReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type CancelLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    int32                  `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	LikeId        int64                  `protobuf:"varint,3,opt,name=likeId,proto3" json:"likeId,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLikeReq) Reset() {
	*x = CancelLikeReq{}
	mi := &file_proto_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLikeReq) ProtoMessage() {}

func (x *CancelLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLikeReq.ProtoReflect.Descriptor instead.
func (*CancelLikeReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{1}
}

func (x *CancelLikeReq) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *CancelLikeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelLikeReq) GetLikeId() int64 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

func (x *CancelLikeReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type ListUserLikesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    int32                  `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserLikesReq) Reset() {
	*x = ListUserLikesReq{}
	mi := &file_proto_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserLikesReq) ProtoMessage() {}

func (x *ListUserLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserLikesReq.ProtoReflect.Descriptor instead.
func (*ListUserLikesReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserLikesReq) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *ListUserLikesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserLikesReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ListUserLikesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUserLikesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeId        []int64                `protobuf:"varint,1,rep,packed,name=likeId,proto3" json:"likeId,omitempty"`
	TimeStamp     []int64                `protobuf:"varint,2,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserLikesResp) Reset() {
	*x = ListUserLikesResp{}
	mi := &file_proto_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserLikesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserLikesResp) ProtoMessage() {}

func (x *ListUserLikesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserLikesResp.ProtoReflect.Descriptor instead.
func (*ListUserLikesResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserLikesResp) GetLikeId() []int64 {
	if x != nil {
		return x.LikeId
	}
	return nil
}

func (x *ListUserLikesResp) GetTimeStamp() []int64 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type ListLikesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    int32                  `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	LikeId        int64                  `protobuf:"varint,2,opt,name=likeId,proto3" json:"likeId,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikesReq) Reset() {
	*x = ListLikesReq{}
	mi := &file_proto_like_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikesReq) ProtoMessage() {}

func (x *ListLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikesReq.ProtoReflect.Descriptor instead.
func (*ListLikesReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{4}
}

func (x *ListLikesReq) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *ListLikesReq) GetLikeId() int64 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

func (x *ListLikesReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *ListLikesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLikesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []int64                `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
	TimeStamp     []int64                `protobuf:"varint,2,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLikesResp) Reset() {
	*x = ListLikesResp{}
	mi := &file_proto_like_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLikesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLikesResp) ProtoMessage() {}

func (x *ListLikesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLikesResp.ProtoReflect.Descriptor instead.
func (*ListLikesResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{5}
}

func (x *ListLikesResp) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ListLikesResp) GetTimeStamp() []int64 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type GetLikeNumsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    int32                  `protobuf:"varint,1,opt,name=businessId,proto3" json:"businessId,omitempty"`
	LikeId        int64                  `protobuf:"varint,2,opt,name=likeId,proto3" json:"likeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeNumsReq) Reset() {
	*x = GetLikeNumsReq{}
	mi := &file_proto_like_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeNumsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeNumsReq) ProtoMessage() {}

func (x *GetLikeNumsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeNumsReq.ProtoReflect.Descriptor instead.
func (*GetLikeNumsReq) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{6}
}

func (x *GetLikeNumsReq) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *GetLikeNumsReq) GetLikeId() int64 {
	if x != nil {
		return x.LikeId
	}
	return 0
}

type GetLikeNumsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Have          bool                   `protobuf:"varint,1,opt,name=have,proto3" json:"have,omitempty"`
	Nums          int64                  `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLikeNumsResp) Reset() {
	*x = GetLikeNumsResp{}
	mi := &file_proto_like_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLikeNumsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLikeNumsResp) ProtoMessage() {}

func (x *GetLikeNumsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLikeNumsResp.ProtoReflect.Descriptor instead.
func (*GetLikeNumsResp) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{7}
}

func (x *GetLikeNumsResp) GetHave() bool {
	if x != nil {
		return x.Have
	}
	return false
}

func (x *GetLikeNumsResp) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_like_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_like_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_like_proto_rawDescGZIP(), []int{8}
}

var File_proto_like_proto protoreflect.FileDescriptor

const file_proto_like_proto_rawDesc = "" +
	"\n" +
	"\x10proto/like.proto\x12\alikeRpc\x1a\x1bgoogle/protobuf/empty.proto\"w\n" +
	"\alikeReq\x12\x1e\n" +
	"\n" +
	"businessId\x18\x01 \x01(\x05R\n" +
	"businessId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06likeId\x18\x03 \x01(\x03R\x06likeId\x12\x1c\n" +
	"\ttimeStamp\x18\x04 \x01(\x03R\ttimeStamp\"}\n" +
	"\rcancelLikeReq\x12\x1e\n" +
	"\n" +
	"businessId\x18\x01 \x01(\x05R\n" +
	"businessId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06likeId\x18\x03 \x01(\x03R\x06likeId\x12\x1c\n" +
	"\ttimeStamp\x18\x04 \x01(\x03R\ttimeStamp\"~\n" +
	"\x10listUserLikesReq\x12\x1e\n" +
	"\n" +
	"businessId\x18\x01 \x01(\x05R\n" +
	"businessId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\ttimeStamp\x18\x03 \x01(\x03R\ttimeStamp\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"I\n" +
	"\x11listUserLikesResp\x12\x16\n" +
	"\x06likeId\x18\x01 \x03(\x03R\x06likeId\x12\x1c\n" +
	"\ttimeStamp\x18\x02 \x03(\x03R\ttimeStamp\"z\n" +
	"\flistLikesReq\x12\x1e\n" +
	"\n" +
	"businessId\x18\x01 \x01(\x05R\n" +
	"businessId\x12\x16\n" +
	"\x06likeId\x18\x02 \x01(\x03R\x06likeId\x12\x1c\n" +
	"\ttimeStamp\x18\x03 \x01(\x03R\ttimeStamp\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"E\n" +
	"\rlistLikesResp\x12\x16\n" +
	"\x06userId\x18\x01 \x03(\x03R\x06userId\x12\x1c\n" +
	"\ttimeStamp\x18\x02 \x03(\x03R\ttimeStamp\"H\n" +
	"\x0egetLikeNumsReq\x12\x1e\n" +
	"\n" +
	"businessId\x18\x01 \x01(\x05R\n" +
	"businessId\x12\x16\n" +
	"\x06likeId\x18\x02 \x01(\x03R\x06likeId\"9\n" +
	"\x0fgetLikeNumsResp\x12\x12\n" +
	"\x04have\x18\x01 \x01(\bR\x04have\x12\x12\n" +
	"\x04nums\x18\x02 \x01(\x03R\x04nums\"\a\n" +
	"\x05empty2\xb3\x02\n" +
	"\vLikeService\x12(\n" +
	"\x04like\x12\x10.likeRpc.likeReq\x1a\x0e.likeRpc.empty\x124\n" +
	"\n" +
	"cancelLike\x12\x16.likeRpc.cancelLikeReq\x1a\x0e.likeRpc.empty\x12F\n" +
	"\rlistUserLikes\x12\x19.likeRpc.listUserLikesReq\x1a\x1a.likeRpc.listUserLikesResp\x12:\n" +
	"\tlistLikes\x12\x15.likeRpc.listLikesReq\x1a\x16.likeRpc.listLikesResp\x12@\n" +
	"\vgetLikeNums\x12\x17.likeRpc.getLikeNumsReq\x1a\x18.likeRpc.getLikeNumsRespB\vZ\t./likeRpcb\x06proto3"

var (
	file_proto_like_proto_rawDescOnce sync.Once
	file_proto_like_proto_rawDescData []byte
)

func file_proto_like_proto_rawDescGZIP() []byte {
	file_proto_like_proto_rawDescOnce.Do(func() {
		file_proto_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)))
	})
	return file_proto_like_proto_rawDescData
}

var file_proto_like_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_like_proto_goTypes = []any{
	(*LikeReq)(nil),           // 0: likeRpc.likeReq
	(*CancelLikeReq)(nil),     // 1: likeRpc.cancelLikeReq
	(*ListUserLikesReq)(nil),  // 2: likeRpc.listUserLikesReq
	(*ListUserLikesResp)(nil), // 3: likeRpc.listUserLikesResp
	(*ListLikesReq)(nil),      // 4: likeRpc.listLikesReq
	(*ListLikesResp)(nil),     // 5: likeRpc.listLikesResp
	(*GetLikeNumsReq)(nil),    // 6: likeRpc.getLikeNumsReq
	(*GetLikeNumsResp)(nil),   // 7: likeRpc.getLikeNumsResp
	(*Empty)(nil),             // 8: likeRpc.empty
}
var file_proto_like_proto_depIdxs = []int32{
	0, // 0: likeRpc.LikeService.like:input_type -> likeRpc.likeReq
	1, // 1: likeRpc.LikeService.cancelLike:input_type -> likeRpc.cancelLikeReq
	2, // 2: likeRpc.LikeService.listUserLikes:input_type -> likeRpc.listUserLikesReq
	4, // 3: likeRpc.LikeService.listLikes:input_type -> likeRpc.listLikesReq
	6, // 4: likeRpc.LikeService.getLikeNums:input_type -> likeRpc.getLikeNumsReq
	8, // 5: likeRpc.LikeService.like:output_type -> likeRpc.empty
	8, // 6: likeRpc.LikeService.cancelLike:output_type -> likeRpc.empty
	3, // 7: likeRpc.LikeService.listUserLikes:output_type -> likeRpc.listUserLikesResp
	5, // 8: likeRpc.LikeService.listLikes:output_type -> likeRpc.listLikesResp
	7, // 9: likeRpc.LikeService.getLikeNums:output_type -> likeRpc.getLikeNumsResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_like_proto_init() }
func file_proto_like_proto_init() {
	if File_proto_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_like_proto_rawDesc), len(file_proto_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_like_proto_goTypes,
		DependencyIndexes: file_proto_like_proto_depIdxs,
		MessageInfos:      file_proto_like_proto_msgTypes,
	}.Build()
	File_proto_like_proto = out.File
	file_proto_like_proto_goTypes = nil
	file_proto_like_proto_depIdxs = nil
}
