// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/publiccontent.proto

package publicContentRpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicContentService_GetUserContentList_FullMethodName = "/publicContentRpc.PublicContentService/getUserContentList"
)

// PublicContentServiceClient is the client API for PublicContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicContentServiceClient interface {
	GetUserContentList(ctx context.Context, in *GetUserContentListReq, opts ...grpc.CallOption) (*GetUserContentListResp, error)
}

type publicContentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicContentServiceClient(cc grpc.ClientConnInterface) PublicContentServiceClient {
	return &publicContentServiceClient{cc}
}

func (c *publicContentServiceClient) GetUserContentList(ctx context.Context, in *GetUserContentListReq, opts ...grpc.CallOption) (*GetUserContentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserContentListResp)
	err := c.cc.Invoke(ctx, PublicContentService_GetUserContentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicContentServiceServer is the server API for PublicContentService service.
// All implementations must embed UnimplementedPublicContentServiceServer
// for forward compatibility.
type PublicContentServiceServer interface {
	GetUserContentList(context.Context, *GetUserContentListReq) (*GetUserContentListResp, error)
	mustEmbedUnimplementedPublicContentServiceServer()
}

// UnimplementedPublicContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicContentServiceServer struct{}

func (UnimplementedPublicContentServiceServer) GetUserContentList(context.Context, *GetUserContentListReq) (*GetUserContentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserContentList not implemented")
}
func (UnimplementedPublicContentServiceServer) mustEmbedUnimplementedPublicContentServiceServer() {}
func (UnimplementedPublicContentServiceServer) testEmbeddedByValue()                              {}

// UnsafePublicContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicContentServiceServer will
// result in compilation errors.
type UnsafePublicContentServiceServer interface {
	mustEmbedUnimplementedPublicContentServiceServer()
}

func RegisterPublicContentServiceServer(s grpc.ServiceRegistrar, srv PublicContentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPublicContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicContentService_ServiceDesc, srv)
}

func _PublicContentService_GetUserContentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserContentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicContentServiceServer).GetUserContentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicContentService_GetUserContentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicContentServiceServer).GetUserContentList(ctx, req.(*GetUserContentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicContentService_ServiceDesc is the grpc.ServiceDesc for PublicContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "publicContentRpc.PublicContentService",
	HandlerType: (*PublicContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserContentList",
			Handler:    _PublicContentService_GetUserContentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/publiccontent.proto",
}
