// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/publiccontent.proto

package publicContentRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserContentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContentListReq) Reset() {
	*x = GetUserContentListReq{}
	mi := &file_proto_publiccontent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContentListReq) ProtoMessage() {}

func (x *GetUserContentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publiccontent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContentListReq.ProtoReflect.Descriptor instead.
func (*GetUserContentListReq) Descriptor() ([]byte, []int) {
	return file_proto_publiccontent_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserContentListReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserContentListReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *GetUserContentListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserContentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int64                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	TimeStamp     []int64                `protobuf:"varint,2,rep,packed,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContentListResp) Reset() {
	*x = GetUserContentListResp{}
	mi := &file_proto_publiccontent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContentListResp) ProtoMessage() {}

func (x *GetUserContentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publiccontent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContentListResp.ProtoReflect.Descriptor instead.
func (*GetUserContentListResp) Descriptor() ([]byte, []int) {
	return file_proto_publiccontent_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserContentListResp) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetUserContentListResp) GetTimeStamp() []int64 {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

var File_proto_publiccontent_proto protoreflect.FileDescriptor

const file_proto_publiccontent_proto_rawDesc = "" +
	"\n" +
	"\x19proto/publiccontent.proto\x12\x10publicContentRpc\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x15getUserContentListReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\ttimeStamp\x18\x02 \x01(\x03R\ttimeStamp\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"F\n" +
	"\x16getUserContentListResp\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x03R\x02id\x12\x1c\n" +
	"\ttimeStamp\x18\x02 \x03(\x03R\ttimeStamp2\x7f\n" +
	"\x14PublicContentService\x12g\n" +
	"\x12getUserContentList\x12'.publicContentRpc.getUserContentListReq\x1a(.publicContentRpc.getUserContentListRespB\x14Z\x12./publicContentRpcb\x06proto3"

var (
	file_proto_publiccontent_proto_rawDescOnce sync.Once
	file_proto_publiccontent_proto_rawDescData []byte
)

func file_proto_publiccontent_proto_rawDescGZIP() []byte {
	file_proto_publiccontent_proto_rawDescOnce.Do(func() {
		file_proto_publiccontent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_publiccontent_proto_rawDesc), len(file_proto_publiccontent_proto_rawDesc)))
	})
	return file_proto_publiccontent_proto_rawDescData
}

var file_proto_publiccontent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_publiccontent_proto_goTypes = []any{
	(*GetUserContentListReq)(nil),  // 0: publicContentRpc.getUserContentListReq
	(*GetUserContentListResp)(nil), // 1: publicContentRpc.getUserContentListResp
}
var file_proto_publiccontent_proto_depIdxs = []int32{
	0, // 0: publicContentRpc.PublicContentService.getUserContentList:input_type -> publicContentRpc.getUserContentListReq
	1, // 1: publicContentRpc.PublicContentService.getUserContentList:output_type -> publicContentRpc.getUserContentListResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_publiccontent_proto_init() }
func file_proto_publiccontent_proto_init() {
	if File_proto_publiccontent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_publiccontent_proto_rawDesc), len(file_proto_publiccontent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_publiccontent_proto_goTypes,
		DependencyIndexes: file_proto_publiccontent_proto_depIdxs,
		MessageInfos:      file_proto_publiccontent_proto_msgTypes,
	}.Build()
	File_proto_publiccontent_proto = out.File
	file_proto_publiccontent_proto_goTypes = nil
	file_proto_publiccontent_proto_depIdxs = nil
}
