version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goflix
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6378:6378"
    volumes:
      - redis_data:/data
    networks:
      - goflix-network
    command: redis-server --port 6378
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6378", "ping"]
      interval: 10s
      retries: 3

  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "--endpoints=http://localhost:2379", "endpoint", "health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - goflix-network

networks:
  goflix-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  etcd_data: