// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/relation.proto

package relationRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowId      int64                  `protobuf:"varint,2,opt,name=followId,proto3" json:"followId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_proto_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowReq) GetFollowId() int64 {
	if x != nil {
		return x.FollowId
	}
	return 0
}

type CancelFollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowId      int64                  `protobuf:"varint,2,opt,name=followId,proto3" json:"followId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFollowReq) Reset() {
	*x = CancelFollowReq{}
	mi := &file_proto_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFollowReq) ProtoMessage() {}

func (x *CancelFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFollowReq.ProtoReflect.Descriptor instead.
func (*CancelFollowReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{1}
}

func (x *CancelFollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelFollowReq) GetFollowId() int64 {
	if x != nil {
		return x.FollowId
	}
	return 0
}

type ListFollowingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	All           bool                   `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingReq) Reset() {
	*x = ListFollowingReq{}
	mi := &file_proto_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingReq) ProtoMessage() {}

func (x *ListFollowingReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingReq.ProtoReflect.Descriptor instead.
func (*ListFollowingReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{2}
}

func (x *ListFollowingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowingReq) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListFollowingReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFollowingReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFollowingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []int64                `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingResp) Reset() {
	*x = ListFollowingResp{}
	mi := &file_proto_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingResp) ProtoMessage() {}

func (x *ListFollowingResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingResp.ProtoReflect.Descriptor instead.
func (*ListFollowingResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{3}
}

func (x *ListFollowingResp) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

type IsFollowingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FollowId      int64                  `protobuf:"varint,2,opt,name=followId,proto3" json:"followId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingReq) Reset() {
	*x = IsFollowingReq{}
	mi := &file_proto_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingReq) ProtoMessage() {}

func (x *IsFollowingReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingReq.ProtoReflect.Descriptor instead.
func (*IsFollowingReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{4}
}

func (x *IsFollowingReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFollowingReq) GetFollowId() int64 {
	if x != nil {
		return x.FollowId
	}
	return 0
}

type IsFollowingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Is            bool                   `protobuf:"varint,1,opt,name=is,proto3" json:"is,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResp) Reset() {
	*x = IsFollowingResp{}
	mi := &file_proto_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResp) ProtoMessage() {}

func (x *IsFollowingResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResp.ProtoReflect.Descriptor instead.
func (*IsFollowingResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{5}
}

func (x *IsFollowingResp) GetIs() bool {
	if x != nil {
		return x.Is
	}
	return false
}

type ListFollowerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowerReq) Reset() {
	*x = ListFollowerReq{}
	mi := &file_proto_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowerReq) ProtoMessage() {}

func (x *ListFollowerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowerReq.ProtoReflect.Descriptor instead.
func (*ListFollowerReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowerReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFollowerReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFollowerReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFollowerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []int64                `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowerResp) Reset() {
	*x = ListFollowerResp{}
	mi := &file_proto_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowerResp) ProtoMessage() {}

func (x *ListFollowerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowerResp.ProtoReflect.Descriptor instead.
func (*ListFollowerResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{7}
}

func (x *ListFollowerResp) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

type GetFollowerNumsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerNumsReq) Reset() {
	*x = GetFollowerNumsReq{}
	mi := &file_proto_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerNumsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerNumsReq) ProtoMessage() {}

func (x *GetFollowerNumsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerNumsReq.ProtoReflect.Descriptor instead.
func (*GetFollowerNumsReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowerNumsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowerNumsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nums          int64                  `protobuf:"varint,1,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowerNumsResp) Reset() {
	*x = GetFollowerNumsResp{}
	mi := &file_proto_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowerNumsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowerNumsResp) ProtoMessage() {}

func (x *GetFollowerNumsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowerNumsResp.ProtoReflect.Descriptor instead.
func (*GetFollowerNumsResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowerNumsResp) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

type GetFollowingNumsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingNumsReq) Reset() {
	*x = GetFollowingNumsReq{}
	mi := &file_proto_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingNumsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingNumsReq) ProtoMessage() {}

func (x *GetFollowingNumsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingNumsReq.ProtoReflect.Descriptor instead.
func (*GetFollowingNumsReq) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{10}
}

func (x *GetFollowingNumsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowingNumsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nums          int64                  `protobuf:"varint,1,opt,name=nums,proto3" json:"nums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingNumsResp) Reset() {
	*x = GetFollowingNumsResp{}
	mi := &file_proto_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingNumsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingNumsResp) ProtoMessage() {}

func (x *GetFollowingNumsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingNumsResp.ProtoReflect.Descriptor instead.
func (*GetFollowingNumsResp) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowingNumsResp) GetNums() int64 {
	if x != nil {
		return x.Nums
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_relation_proto_rawDescGZIP(), []int{12}
}

var File_proto_relation_proto protoreflect.FileDescriptor

const file_proto_relation_proto_rawDesc = "" +
	"\n" +
	"\x14proto/relation.proto\x12\vrelationRpc\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\tfollowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfollowId\x18\x02 \x01(\x03R\bfollowId\"E\n" +
	"\x0fcancelFollowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfollowId\x18\x02 \x01(\x03R\bfollowId\"j\n" +
	"\x10listFollowingReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"+\n" +
	"\x11listFollowingResp\x12\x16\n" +
	"\x06userId\x18\x01 \x03(\x03R\x06userId\"D\n" +
	"\x0eisFollowingReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfollowId\x18\x02 \x01(\x03R\bfollowId\"!\n" +
	"\x0fisFollowingResp\x12\x0e\n" +
	"\x02is\x18\x01 \x01(\bR\x02is\"W\n" +
	"\x0flistFollowerReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"*\n" +
	"\x10listFollowerResp\x12\x16\n" +
	"\x06userId\x18\x01 \x03(\x03R\x06userId\",\n" +
	"\x12getFollowerNumsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\")\n" +
	"\x13getFollowerNumsResp\x12\x12\n" +
	"\x04nums\x18\x01 \x01(\x03R\x04nums\"-\n" +
	"\x13getFollowingNumsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"*\n" +
	"\x14getFollowingNumsResp\x12\x12\n" +
	"\x04nums\x18\x01 \x01(\x03R\x04nums\"\a\n" +
	"\x05Empty2\x9f\x04\n" +
	"\x0fRelationService\x124\n" +
	"\x06follow\x12\x16.relationRpc.followReq\x1a\x12.relationRpc.Empty\x12@\n" +
	"\fcancelFollow\x12\x1c.relationRpc.cancelFollowReq\x1a\x12.relationRpc.Empty\x12N\n" +
	"\rlistFollowing\x12\x1d.relationRpc.listFollowingReq\x1a\x1e.relationRpc.listFollowingResp\x12H\n" +
	"\visFollowing\x12\x1b.relationRpc.isFollowingReq\x1a\x1c.relationRpc.isFollowingResp\x12K\n" +
	"\flistFollower\x12\x1c.relationRpc.listFollowerReq\x1a\x1d.relationRpc.listFollowerResp\x12W\n" +
	"\x10getFollowingNums\x12 .relationRpc.getFollowingNumsReq\x1a!.relationRpc.getFollowingNumsResp\x12T\n" +
	"\x0fgetFollowerNums\x12\x1f.relationRpc.getFollowerNumsReq\x1a .relationRpc.getFollowerNumsRespB\x0fZ\r./relationRpcb\x06proto3"

var (
	file_proto_relation_proto_rawDescOnce sync.Once
	file_proto_relation_proto_rawDescData []byte
)

func file_proto_relation_proto_rawDescGZIP() []byte {
	file_proto_relation_proto_rawDescOnce.Do(func() {
		file_proto_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_relation_proto_rawDesc), len(file_proto_relation_proto_rawDesc)))
	})
	return file_proto_relation_proto_rawDescData
}

var file_proto_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_relation_proto_goTypes = []any{
	(*FollowReq)(nil),            // 0: relationRpc.followReq
	(*CancelFollowReq)(nil),      // 1: relationRpc.cancelFollowReq
	(*ListFollowingReq)(nil),     // 2: relationRpc.listFollowingReq
	(*ListFollowingResp)(nil),    // 3: relationRpc.listFollowingResp
	(*IsFollowingReq)(nil),       // 4: relationRpc.isFollowingReq
	(*IsFollowingResp)(nil),      // 5: relationRpc.isFollowingResp
	(*ListFollowerReq)(nil),      // 6: relationRpc.listFollowerReq
	(*ListFollowerResp)(nil),     // 7: relationRpc.listFollowerResp
	(*GetFollowerNumsReq)(nil),   // 8: relationRpc.getFollowerNumsReq
	(*GetFollowerNumsResp)(nil),  // 9: relationRpc.getFollowerNumsResp
	(*GetFollowingNumsReq)(nil),  // 10: relationRpc.getFollowingNumsReq
	(*GetFollowingNumsResp)(nil), // 11: relationRpc.getFollowingNumsResp
	(*Empty)(nil),                // 12: relationRpc.Empty
}
var file_proto_relation_proto_depIdxs = []int32{
	0,  // 0: relationRpc.RelationService.follow:input_type -> relationRpc.followReq
	1,  // 1: relationRpc.RelationService.cancelFollow:input_type -> relationRpc.cancelFollowReq
	2,  // 2: relationRpc.RelationService.listFollowing:input_type -> relationRpc.listFollowingReq
	4,  // 3: relationRpc.RelationService.isFollowing:input_type -> relationRpc.isFollowingReq
	6,  // 4: relationRpc.RelationService.listFollower:input_type -> relationRpc.listFollowerReq
	10, // 5: relationRpc.RelationService.getFollowingNums:input_type -> relationRpc.getFollowingNumsReq
	8,  // 6: relationRpc.RelationService.getFollowerNums:input_type -> relationRpc.getFollowerNumsReq
	12, // 7: relationRpc.RelationService.follow:output_type -> relationRpc.Empty
	12, // 8: relationRpc.RelationService.cancelFollow:output_type -> relationRpc.Empty
	3,  // 9: relationRpc.RelationService.listFollowing:output_type -> relationRpc.listFollowingResp
	5,  // 10: relationRpc.RelationService.isFollowing:output_type -> relationRpc.isFollowingResp
	7,  // 11: relationRpc.RelationService.listFollower:output_type -> relationRpc.listFollowerResp
	11, // 12: relationRpc.RelationService.getFollowingNums:output_type -> relationRpc.getFollowingNumsResp
	9,  // 13: relationRpc.RelationService.getFollowerNums:output_type -> relationRpc.getFollowerNumsResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_relation_proto_init() }
func file_proto_relation_proto_init() {
	if File_proto_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_relation_proto_rawDesc), len(file_proto_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_relation_proto_goTypes,
		DependencyIndexes: file_proto_relation_proto_depIdxs,
		MessageInfos:      file_proto_relation_proto_msgTypes,
	}.Build()
	File_proto_relation_proto = out.File
	file_proto_relation_proto_goTypes = nil
	file_proto_relation_proto_depIdxs = nil
}
