// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: publiccontent.proto

package server

import (
	"context"

	"GoFlix/services/content/public/internal/logic"
	"GoFlix/services/content/public/internal/svc"
	"GoFlix/services/content/public/publicContentRpc"
)

type PublicContentServiceServer struct {
	svcCtx *svc.ServiceContext
	publicContentRpc.UnimplementedPublicContentServiceServer
}

func NewPublicContentServiceServer(svcCtx *svc.ServiceContext) *PublicContentServiceServer {
	return &PublicContentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PublicContentServiceServer) GetUserContentList(ctx context.Context, in *publicContentRpc.GetUserContentListReq) (*publicContentRpc.GetUserContentListResp, error) {
	l := logic.NewGetUserContentListLogic(ctx, s.svcCtx)
	return l.GetUserContentList(in)
}
