// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/metacontent.proto

package metaContentRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ShortText     string                 `protobuf:"bytes,3,opt,name=shortText,proto3" json:"shortText,omitempty"`
	LongTextUri   string                 `protobuf:"bytes,4,opt,name=longTextUri,proto3" json:"longTextUri,omitempty"`
	PhotoUriList  []string               `protobuf:"bytes,5,rep,name=photoUriList,proto3" json:"photoUriList,omitempty"`
	VideoUriList  []string               `protobuf:"bytes,6,rep,name=videoUriList,proto3" json:"videoUriList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_proto_metacontent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{0}
}

func (x *PublishReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishReq) GetShortText() string {
	if x != nil {
		return x.ShortText
	}
	return ""
}

func (x *PublishReq) GetLongTextUri() string {
	if x != nil {
		return x.LongTextUri
	}
	return ""
}

func (x *PublishReq) GetPhotoUriList() []string {
	if x != nil {
		return x.PhotoUriList
	}
	return nil
}

func (x *PublishReq) GetVideoUriList() []string {
	if x != nil {
		return x.VideoUriList
	}
	return nil
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ShortText     string                 `protobuf:"bytes,4,opt,name=shortText,proto3" json:"shortText,omitempty"`
	LongTextUri   string                 `protobuf:"bytes,5,opt,name=longTextUri,proto3" json:"longTextUri,omitempty"`
	PhotoUriList  []string               `protobuf:"bytes,6,rep,name=photoUriList,proto3" json:"photoUriList,omitempty"`
	VideoUriList  []string               `protobuf:"bytes,7,rep,name=videoUriList,proto3" json:"videoUriList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_proto_metacontent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *UpdateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateReq) GetShortText() string {
	if x != nil {
		return x.ShortText
	}
	return ""
}

func (x *UpdateReq) GetLongTextUri() string {
	if x != nil {
		return x.LongTextUri
	}
	return ""
}

func (x *UpdateReq) GetPhotoUriList() []string {
	if x != nil {
		return x.PhotoUriList
	}
	return nil
}

func (x *UpdateReq) GetVideoUriList() []string {
	if x != nil {
		return x.VideoUriList
	}
	return nil
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_proto_metacontent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *DeleteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type StatusSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ContentId     int64                  `protobuf:"varint,2,opt,name=contentId,proto3" json:"contentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusSearchReq) Reset() {
	*x = StatusSearchReq{}
	mi := &file_proto_metacontent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSearchReq) ProtoMessage() {}

func (x *StatusSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSearchReq.ProtoReflect.Descriptor instead.
func (*StatusSearchReq) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusSearchReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StatusSearchReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

type StatusSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusSearchResp) Reset() {
	*x = StatusSearchResp{}
	mi := &file_proto_metacontent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSearchResp) ProtoMessage() {}

func (x *StatusSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSearchResp.ProtoReflect.Descriptor instead.
func (*StatusSearchResp) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{4}
}

func (x *StatusSearchResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StatusSearchResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_metacontent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metacontent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_metacontent_proto_rawDescGZIP(), []int{5}
}

var File_proto_metacontent_proto protoreflect.FileDescriptor

const file_proto_metacontent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/metacontent.proto\x12\x0emetaContentRpc\x1a\x1bgoogle/protobuf/empty.proto\"\xc2\x01\n" +
	"\n" +
	"publishReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tshortText\x18\x03 \x01(\tR\tshortText\x12 \n" +
	"\vlongTextUri\x18\x04 \x01(\tR\vlongTextUri\x12\"\n" +
	"\fphotoUriList\x18\x05 \x03(\tR\fphotoUriList\x12\"\n" +
	"\fvideoUriList\x18\x06 \x03(\tR\fvideoUriList\"\xdf\x01\n" +
	"\tupdateReq\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\x03R\tcontentId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tshortText\x18\x04 \x01(\tR\tshortText\x12 \n" +
	"\vlongTextUri\x18\x05 \x01(\tR\vlongTextUri\x12\"\n" +
	"\fphotoUriList\x18\x06 \x03(\tR\fphotoUriList\x12\"\n" +
	"\fvideoUriList\x18\a \x03(\tR\fvideoUriList\"A\n" +
	"\tdeleteReq\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\x03R\tcontentId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"G\n" +
	"\x0fstatusSearchReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcontentId\x18\x02 \x01(\x03R\tcontentId\">\n" +
	"\x10statusSearchResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"\a\n" +
	"\x05empty2\x9d\x02\n" +
	"\x12MetaContentService\x12<\n" +
	"\apublish\x12\x1a.metaContentRpc.publishReq\x1a\x15.metaContentRpc.empty\x12:\n" +
	"\x06update\x12\x19.metaContentRpc.updateReq\x1a\x15.metaContentRpc.empty\x12:\n" +
	"\x06delete\x12\x19.metaContentRpc.deleteReq\x1a\x15.metaContentRpc.empty\x12Q\n" +
	"\fstatusSearch\x12\x1f.metaContentRpc.statusSearchReq\x1a .metaContentRpc.statusSearchRespB\x12Z\x10./metaContentRpcb\x06proto3"

var (
	file_proto_metacontent_proto_rawDescOnce sync.Once
	file_proto_metacontent_proto_rawDescData []byte
)

func file_proto_metacontent_proto_rawDescGZIP() []byte {
	file_proto_metacontent_proto_rawDescOnce.Do(func() {
		file_proto_metacontent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metacontent_proto_rawDesc), len(file_proto_metacontent_proto_rawDesc)))
	})
	return file_proto_metacontent_proto_rawDescData
}

var file_proto_metacontent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_metacontent_proto_goTypes = []any{
	(*PublishReq)(nil),       // 0: metaContentRpc.publishReq
	(*UpdateReq)(nil),        // 1: metaContentRpc.updateReq
	(*DeleteReq)(nil),        // 2: metaContentRpc.deleteReq
	(*StatusSearchReq)(nil),  // 3: metaContentRpc.statusSearchReq
	(*StatusSearchResp)(nil), // 4: metaContentRpc.statusSearchResp
	(*Empty)(nil),            // 5: metaContentRpc.empty
}
var file_proto_metacontent_proto_depIdxs = []int32{
	0, // 0: metaContentRpc.MetaContentService.publish:input_type -> metaContentRpc.publishReq
	1, // 1: metaContentRpc.MetaContentService.update:input_type -> metaContentRpc.updateReq
	2, // 2: metaContentRpc.MetaContentService.delete:input_type -> metaContentRpc.deleteReq
	3, // 3: metaContentRpc.MetaContentService.statusSearch:input_type -> metaContentRpc.statusSearchReq
	5, // 4: metaContentRpc.MetaContentService.publish:output_type -> metaContentRpc.empty
	5, // 5: metaContentRpc.MetaContentService.update:output_type -> metaContentRpc.empty
	5, // 6: metaContentRpc.MetaContentService.delete:output_type -> metaContentRpc.empty
	4, // 7: metaContentRpc.MetaContentService.statusSearch:output_type -> metaContentRpc.statusSearchResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metacontent_proto_init() }
func file_proto_metacontent_proto_init() {
	if File_proto_metacontent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metacontent_proto_rawDesc), len(file_proto_metacontent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metacontent_proto_goTypes,
		DependencyIndexes: file_proto_metacontent_proto_depIdxs,
		MessageInfos:      file_proto_metacontent_proto_msgTypes,
	}.Build()
	File_proto_metacontent_proto = out.File
	file_proto_metacontent_proto_goTypes = nil
	file_proto_metacontent_proto_depIdxs = nil
}
