// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: like.proto

package server

import (
	"context"

	"GoFlix/services/like/internal/logic"
	"GoFlix/services/like/internal/svc"
	"GoFlix/services/like/likeRpc"
)

type LikeServiceServer struct {
	svcCtx *svc.ServiceContext
	likeRpc.UnimplementedLikeServiceServer
}

func NewLikeServiceServer(svcCtx *svc.ServiceContext) *LikeServiceServer {
	return &LikeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServiceServer) Like(ctx context.Context, in *likeRpc.LikeReq) (*likeRpc.Empty, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}

func (s *LikeServiceServer) CancelLike(ctx context.Context, in *likeRpc.CancelLikeReq) (*likeRpc.Empty, error) {
	l := logic.NewCancelLikeLogic(ctx, s.svcCtx)
	return l.CancelLike(in)
}

func (s *LikeServiceServer) ListUserLikes(ctx context.Context, in *likeRpc.ListUserLikesReq) (*likeRpc.ListUserLikesResp, error) {
	l := logic.NewListUserLikesLogic(ctx, s.svcCtx)
	return l.ListUserLikes(in)
}

func (s *LikeServiceServer) ListLikes(ctx context.Context, in *likeRpc.ListLikesReq) (*likeRpc.ListLikesResp, error) {
	l := logic.NewListLikesLogic(ctx, s.svcCtx)
	return l.ListLikes(in)
}

func (s *LikeServiceServer) GetLikeNums(ctx context.Context, in *likeRpc.GetLikeNumsReq) (*likeRpc.GetLikeNumsResp, error) {
	l := logic.NewGetLikeNumsLogic(ctx, s.svcCtx)
	return l.GetLikeNums(in)
}
