// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: auth.proto

package server

import (
	"context"

	"GoFlix/services/auth/authRpc"
	"GoFlix/services/auth/internal/logic"
	"GoFlix/services/auth/internal/svc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	authRpc.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Authentication(ctx context.Context, in *authRpc.AuthenticationReq) (*authRpc.AuthenticationResp, error) {
	l := logic.NewAuthenticationLogic(ctx, s.svcCtx)
	return l.Authentication(in)
}

func (s *AuthServiceServer) RefreshSession(ctx context.Context, in *authRpc.RefreshSessionReq) (*authRpc.RefreshSessionResp, error) {
	l := logic.NewRefreshSessionLogic(ctx, s.svcCtx)
	return l.RefreshSession(in)
}

func (s *AuthServiceServer) DeleteSession(ctx context.Context, in *authRpc.DeleteSessionReq) (*authRpc.DeleteSessionResp, error) {
	l := logic.NewDeleteSessionLogic(ctx, s.svcCtx)
	return l.DeleteSession(in)
}

func (s *AuthServiceServer) CreateVoucher(ctx context.Context, in *authRpc.CreateVoucherReq) (*authRpc.CreateVoucherResp, error) {
	l := logic.NewCreateVoucherLogic(ctx, s.svcCtx)
	return l.CreateVoucher(in)
}
