// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/comment.proto

package commentRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ContentId     int64                  `protobuf:"varint,2,opt,name=contentId,proto3" json:"contentId,omitempty"`
	RootId        int64                  `protobuf:"varint,3,opt,name=rootId,proto3" json:"rootId,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	ShortText     string                 `protobuf:"bytes,5,opt,name=shortText,proto3" json:"shortText,omitempty"`
	LongTextUri   string                 `protobuf:"bytes,6,opt,name=longTextUri,proto3" json:"longTextUri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentReq) Reset() {
	*x = CommentReq{}
	mi := &file_proto_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentReq) ProtoMessage() {}

func (x *CommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentReq.ProtoReflect.Descriptor instead.
func (*CommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *CommentReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentReq) GetShortText() string {
	if x != nil {
		return x.ShortText
	}
	return ""
}

func (x *CommentReq) GetLongTextUri() string {
	if x != nil {
		return x.LongTextUri
	}
	return ""
}

type DelCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCommentReq) Reset() {
	*x = DelCommentReq{}
	mi := &file_proto_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCommentReq) ProtoMessage() {}

func (x *DelCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCommentReq.ProtoReflect.Descriptor instead.
func (*DelCommentReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{1}
}

func (x *DelCommentReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DelCommentReq) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentListByHotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListByHotReq) Reset() {
	*x = GetCommentListByHotReq{}
	mi := &file_proto_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListByHotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListByHotReq) ProtoMessage() {}

func (x *GetCommentListByHotReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListByHotReq.ProtoReflect.Descriptor instead.
func (*GetCommentListByHotReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{2}
}

func (x *GetCommentListByHotReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *GetCommentListByHotReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCommentListByHotReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetCommentListByTimeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentListByTimeReq) Reset() {
	*x = GetCommentListByTimeReq{}
	mi := &file_proto_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentListByTimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListByTimeReq) ProtoMessage() {}

func (x *GetCommentListByTimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListByTimeReq.ProtoReflect.Descriptor instead.
func (*GetCommentListByTimeReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommentListByTimeReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *GetCommentListByTimeReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCommentListByTimeReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type GetReplyCommentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     int64                  `protobuf:"varint,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	RootId        int64                  `protobuf:"varint,2,opt,name=rootId,proto3" json:"rootId,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplyCommentListReq) Reset() {
	*x = GetReplyCommentListReq{}
	mi := &file_proto_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplyCommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplyCommentListReq) ProtoMessage() {}

func (x *GetReplyCommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplyCommentListReq.ProtoReflect.Descriptor instead.
func (*GetReplyCommentListReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{4}
}

func (x *GetReplyCommentListReq) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *GetReplyCommentListReq) GetRootId() int64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *GetReplyCommentListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReplyCommentListReq) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type CommentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     []int64                `protobuf:"varint,1,rep,packed,name=CommentId,proto3" json:"CommentId,omitempty"`
	UserId        []int64                `protobuf:"varint,2,rep,packed,name=UserId,proto3" json:"UserId,omitempty"`
	ContentId     []int64                `protobuf:"varint,3,rep,packed,name=ContentId,proto3" json:"ContentId,omitempty"`
	RootId        []int64                `protobuf:"varint,4,rep,packed,name=RootId,proto3" json:"RootId,omitempty"`
	ParentId      []int64                `protobuf:"varint,5,rep,packed,name=ParentId,proto3" json:"ParentId,omitempty"`
	CreatedAt     []int64                `protobuf:"varint,6,rep,packed,name=createdAt,proto3" json:"createdAt,omitempty"`
	ShortText     []string               `protobuf:"bytes,7,rep,name=ShortText,proto3" json:"ShortText,omitempty"`
	LongTextUri   []string               `protobuf:"bytes,8,rep,name=LongTextUri,proto3" json:"LongTextUri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	mi := &file_proto_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{5}
}

func (x *CommentListResp) GetCommentId() []int64 {
	if x != nil {
		return x.CommentId
	}
	return nil
}

func (x *CommentListResp) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *CommentListResp) GetContentId() []int64 {
	if x != nil {
		return x.ContentId
	}
	return nil
}

func (x *CommentListResp) GetRootId() []int64 {
	if x != nil {
		return x.RootId
	}
	return nil
}

func (x *CommentListResp) GetParentId() []int64 {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *CommentListResp) GetCreatedAt() []int64 {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommentListResp) GetShortText() []string {
	if x != nil {
		return x.ShortText
	}
	return nil
}

func (x *CommentListResp) GetLongTextUri() []string {
	if x != nil {
		return x.LongTextUri
	}
	return nil
}

type GetCommentCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Business      int32                  `protobuf:"varint,1,opt,name=business,proto3" json:"business,omitempty"`
	CountId       int64                  `protobuf:"varint,2,opt,name=countId,proto3" json:"countId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentCountReq) Reset() {
	*x = GetCommentCountReq{}
	mi := &file_proto_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentCountReq) ProtoMessage() {}

func (x *GetCommentCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentCountReq.ProtoReflect.Descriptor instead.
func (*GetCommentCountReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentCountReq) GetBusiness() int32 {
	if x != nil {
		return x.Business
	}
	return 0
}

func (x *GetCommentCountReq) GetCountId() int64 {
	if x != nil {
		return x.CountId
	}
	return 0
}

type GetCommentCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentCountResp) Reset() {
	*x = GetCommentCountResp{}
	mi := &file_proto_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentCountResp) ProtoMessage() {}

func (x *GetCommentCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentCountResp.ProtoReflect.Descriptor instead.
func (*GetCommentCountResp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommentCountResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{8}
}

var File_proto_comment_proto protoreflect.FileDescriptor

const file_proto_comment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/comment.proto\x12\n" +
	"commentRpc\x1a\x1bgoogle/protobuf/empty.proto\"\xb6\x01\n" +
	"\n" +
	"commentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcontentId\x18\x02 \x01(\x03R\tcontentId\x12\x16\n" +
	"\x06rootId\x18\x03 \x01(\x03R\x06rootId\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x03R\bparentId\x12\x1c\n" +
	"\tshortText\x18\x05 \x01(\tR\tshortText\x12 \n" +
	"\vlongTextUri\x18\x06 \x01(\tR\vlongTextUri\"E\n" +
	"\rdelCommentReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tcommentId\x18\x02 \x01(\x03R\tcommentId\"d\n" +
	"\x16getCommentListByHotReq\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\x03R\tcontentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"k\n" +
	"\x17getCommentListByTimeReq\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\x03R\tcontentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\ttimeStamp\x18\x03 \x01(\x03R\ttimeStamp\"\x82\x01\n" +
	"\x16getReplyCommentListReq\x12\x1c\n" +
	"\tcontentId\x18\x01 \x01(\x03R\tcontentId\x12\x16\n" +
	"\x06rootId\x18\x02 \x01(\x03R\x06rootId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1c\n" +
	"\ttimeStamp\x18\x04 \x01(\x03R\ttimeStamp\"\xf7\x01\n" +
	"\x0fCommentListResp\x12\x1c\n" +
	"\tCommentId\x18\x01 \x03(\x03R\tCommentId\x12\x16\n" +
	"\x06UserId\x18\x02 \x03(\x03R\x06UserId\x12\x1c\n" +
	"\tContentId\x18\x03 \x03(\x03R\tContentId\x12\x16\n" +
	"\x06RootId\x18\x04 \x03(\x03R\x06RootId\x12\x1a\n" +
	"\bParentId\x18\x05 \x03(\x03R\bParentId\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x03(\x03R\tcreatedAt\x12\x1c\n" +
	"\tShortText\x18\a \x03(\tR\tShortText\x12 \n" +
	"\vLongTextUri\x18\b \x03(\tR\vLongTextUri\"J\n" +
	"\x12getCommentCountReq\x12\x1a\n" +
	"\bbusiness\x18\x01 \x01(\x05R\bbusiness\x12\x18\n" +
	"\acountId\x18\x02 \x01(\x03R\acountId\"+\n" +
	"\x13getCommentCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\a\n" +
	"\x05empty2\xe0\x03\n" +
	"\x0eCommentService\x124\n" +
	"\acomment\x12\x16.commentRpc.commentReq\x1a\x11.commentRpc.empty\x12:\n" +
	"\n" +
	"delComment\x12\x19.commentRpc.delCommentReq\x1a\x11.commentRpc.empty\x12V\n" +
	"\x13getCommentListByHot\x12\".commentRpc.getCommentListByHotReq\x1a\x1b.commentRpc.CommentListResp\x12X\n" +
	"\x14getCommentListByTime\x12#.commentRpc.getCommentListByTimeReq\x1a\x1b.commentRpc.CommentListResp\x12V\n" +
	"\x13getReplyCommentList\x12\".commentRpc.getReplyCommentListReq\x1a\x1b.commentRpc.CommentListResp\x12R\n" +
	"\x0fgetCommentCount\x12\x1e.commentRpc.getCommentCountReq\x1a\x1f.commentRpc.getCommentCountRespB\x0eZ\f./commentRpcb\x06proto3"

var (
	file_proto_comment_proto_rawDescOnce sync.Once
	file_proto_comment_proto_rawDescData []byte
)

func file_proto_comment_proto_rawDescGZIP() []byte {
	file_proto_comment_proto_rawDescOnce.Do(func() {
		file_proto_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)))
	})
	return file_proto_comment_proto_rawDescData
}

var file_proto_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_comment_proto_goTypes = []any{
	(*CommentReq)(nil),              // 0: commentRpc.commentReq
	(*DelCommentReq)(nil),           // 1: commentRpc.delCommentReq
	(*GetCommentListByHotReq)(nil),  // 2: commentRpc.getCommentListByHotReq
	(*GetCommentListByTimeReq)(nil), // 3: commentRpc.getCommentListByTimeReq
	(*GetReplyCommentListReq)(nil),  // 4: commentRpc.getReplyCommentListReq
	(*CommentListResp)(nil),         // 5: commentRpc.CommentListResp
	(*GetCommentCountReq)(nil),      // 6: commentRpc.getCommentCountReq
	(*GetCommentCountResp)(nil),     // 7: commentRpc.getCommentCountResp
	(*Empty)(nil),                   // 8: commentRpc.empty
}
var file_proto_comment_proto_depIdxs = []int32{
	0, // 0: commentRpc.CommentService.comment:input_type -> commentRpc.commentReq
	1, // 1: commentRpc.CommentService.delComment:input_type -> commentRpc.delCommentReq
	2, // 2: commentRpc.CommentService.getCommentListByHot:input_type -> commentRpc.getCommentListByHotReq
	3, // 3: commentRpc.CommentService.getCommentListByTime:input_type -> commentRpc.getCommentListByTimeReq
	4, // 4: commentRpc.CommentService.getReplyCommentList:input_type -> commentRpc.getReplyCommentListReq
	6, // 5: commentRpc.CommentService.getCommentCount:input_type -> commentRpc.getCommentCountReq
	8, // 6: commentRpc.CommentService.comment:output_type -> commentRpc.empty
	8, // 7: commentRpc.CommentService.delComment:output_type -> commentRpc.empty
	5, // 8: commentRpc.CommentService.getCommentListByHot:output_type -> commentRpc.CommentListResp
	5, // 9: commentRpc.CommentService.getCommentListByTime:output_type -> commentRpc.CommentListResp
	5, // 10: commentRpc.CommentService.getReplyCommentList:output_type -> commentRpc.CommentListResp
	7, // 11: commentRpc.CommentService.getCommentCount:output_type -> commentRpc.getCommentCountResp
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_comment_proto_init() }
func file_proto_comment_proto_init() {
	if File_proto_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comment_proto_goTypes,
		DependencyIndexes: file_proto_comment_proto_depIdxs,
		MessageInfos:      file_proto_comment_proto_msgTypes,
	}.Build()
	File_proto_comment_proto = out.File
	file_proto_comment_proto_goTypes = nil
	file_proto_comment_proto_depIdxs = nil
}
