// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/auth.proto

package authRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationReq) Reset() {
	*x = AuthenticationReq{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationReq) ProtoMessage() {}

func (x *AuthenticationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationReq.ProtoReflect.Descriptor instead.
func (*AuthenticationReq) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthenticationReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pass          bool                   `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResp) Reset() {
	*x = AuthenticationResp{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResp) ProtoMessage() {}

func (x *AuthenticationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResp.ProtoReflect.Descriptor instead.
func (*AuthenticationResp) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationResp) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *AuthenticationResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionReq) Reset() {
	*x = RefreshSessionReq{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionReq) ProtoMessage() {}

func (x *RefreshSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionReq.ProtoReflect.Descriptor instead.
func (*RefreshSessionReq) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionReq) Reset() {
	*x = DeleteSessionReq{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionReq) ProtoMessage() {}

func (x *DeleteSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionReq.ProtoReflect.Descriptor instead.
func (*DeleteSessionReq) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResp) Reset() {
	*x = DeleteSessionResp{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResp) ProtoMessage() {}

func (x *DeleteSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResp.ProtoReflect.Descriptor instead.
func (*DeleteSessionResp) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

type RefreshSessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResp) Reset() {
	*x = RefreshSessionResp{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResp) ProtoMessage() {}

func (x *RefreshSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResp.ProtoReflect.Descriptor instead.
func (*RefreshSessionResp) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshSessionResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RefreshSessionResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateVoucherReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVoucherReq) Reset() {
	*x = CreateVoucherReq{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVoucherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoucherReq) ProtoMessage() {}

func (x *CreateVoucherReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoucherReq.ProtoReflect.Descriptor instead.
func (*CreateVoucherReq) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVoucherReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateVoucherResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVoucherResp) Reset() {
	*x = CreateVoucherResp{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVoucherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoucherResp) ProtoMessage() {}

func (x *CreateVoucherResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoucherResp.ProtoReflect.Descriptor instead.
func (*CreateVoucherResp) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVoucherResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateVoucherResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateVoucherResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\aauthRpc\"G\n" +
	"\x11AuthenticationReq\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\">\n" +
	"\x12AuthenticationResp\x12\x12\n" +
	"\x04pass\x18\x01 \x01(\bR\x04pass\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"1\n" +
	"\x11RefreshSessionReq\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\"0\n" +
	"\x10DeleteSessionReq\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\"\x13\n" +
	"\x11DeleteSessionResp\":\n" +
	"\x12RefreshSessionResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"*\n" +
	"\x10CreateVoucherReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"W\n" +
	"\x11CreateVoucherResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token2\xbb\x02\n" +
	"\vAuthService\x12K\n" +
	"\x0eAuthentication\x12\x1a.authRpc.AuthenticationReq\x1a\x1b.authRpc.AuthenticationResp\"\x00\x12K\n" +
	"\x0eRefreshSession\x12\x1a.authRpc.RefreshSessionReq\x1a\x1b.authRpc.RefreshSessionResp\"\x00\x12H\n" +
	"\rDeleteSession\x12\x19.authRpc.DeleteSessionReq\x1a\x1a.authRpc.DeleteSessionResp\"\x00\x12H\n" +
	"\rCreateVoucher\x12\x19.authRpc.CreateVoucherReq\x1a\x1a.authRpc.CreateVoucherResp\"\x00B\vZ\t./authRpcb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_auth_proto_goTypes = []any{
	(*AuthenticationReq)(nil),  // 0: authRpc.AuthenticationReq
	(*AuthenticationResp)(nil), // 1: authRpc.AuthenticationResp
	(*RefreshSessionReq)(nil),  // 2: authRpc.RefreshSessionReq
	(*DeleteSessionReq)(nil),   // 3: authRpc.DeleteSessionReq
	(*DeleteSessionResp)(nil),  // 4: authRpc.DeleteSessionResp
	(*RefreshSessionResp)(nil), // 5: authRpc.RefreshSessionResp
	(*CreateVoucherReq)(nil),   // 6: authRpc.CreateVoucherReq
	(*CreateVoucherResp)(nil),  // 7: authRpc.CreateVoucherResp
}
var file_proto_auth_proto_depIdxs = []int32{
	0, // 0: authRpc.AuthService.Authentication:input_type -> authRpc.AuthenticationReq
	2, // 1: authRpc.AuthService.RefreshSession:input_type -> authRpc.RefreshSessionReq
	3, // 2: authRpc.AuthService.DeleteSession:input_type -> authRpc.DeleteSessionReq
	6, // 3: authRpc.AuthService.CreateVoucher:input_type -> authRpc.CreateVoucherReq
	1, // 4: authRpc.AuthService.Authentication:output_type -> authRpc.AuthenticationResp
	5, // 5: authRpc.AuthService.RefreshSession:output_type -> authRpc.RefreshSessionResp
	4, // 6: authRpc.AuthService.DeleteSession:output_type -> authRpc.DeleteSessionResp
	7, // 7: authRpc.AuthService.CreateVoucher:output_type -> authRpc.CreateVoucherResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
